# Generated by Django 2.0.2 on 2018-02-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=100)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
    ]
